using Terraria.ModLoader;
using Terraria.ID;
using AbslbEasy;

namespace AbslbEasy
{
    
    public class AbslbEasy : Mod
	{
        public static Mod Instance;
        public override void Load()
        {
            Instance = this;
        }
        public override void AddRecipes()
        {
            ModRecipe recipe = new ModRecipe(this);
            recipe.AddIngredient(ItemID.GoldBar, 5);
            recipe.AddIngredient(ItemID.IronBar, 2);
            recipe.AddTile(TileID.HeavyWorkBench);
            recipe.SetResult(ItemID.Compass, 1);
            recipe.anyIronBar = true;
            recipe.AddRecipe();
            ModRecipe recipe2 = new ModRecipe(this);
            recipe2.AddIngredient(ItemID.PlatinumBar, 5);
            recipe2.AddIngredient(ItemID.IronBar, 2);
            recipe2.AddTile(TileID.HeavyWorkBench);
            recipe2.SetResult(ItemID.Compass, 1);
            recipe2.anyIronBar = true;
            recipe2.AddRecipe();

            ModRecipe recipe3 = new ModRecipe(this);
            recipe3.AddIngredient(ItemID.SilverBar, 10);
            recipe3.AddIngredient(ItemID.IronBar, 2);
            recipe3.AddIngredient(ItemID.Chain, 3);
            recipe3.AddTile(TileID.HeavyWorkBench);
            recipe3.SetResult(ItemID.DepthMeter, 1);
            recipe3.anyIronBar = true;
            recipe3.AddRecipe();
            ModRecipe recipe4 = new ModRecipe(this);
            recipe4.AddIngredient(ItemID.TungstenBar, 10);
            recipe4.AddIngredient(ItemID.IronBar, 2);
            recipe4.AddIngredient(ItemID.Chain, 3);
            recipe4.AddTile(TileID.HeavyWorkBench);
            recipe4.SetResult(ItemID.DepthMeter, 1);
            recipe4.anyIronBar = true;
            recipe4.AddRecipe();

            ModRecipe recipe5 = new ModRecipe(this);
            recipe5.AddIngredient(ItemID.SilverBar, 10);
            recipe5.AddIngredient(ItemID.IronBar, 2);
            recipe5.AddIngredient(ItemID.SnowBlock, 30);
            recipe5.AddTile(TileID.HeavyWorkBench);
            recipe5.SetResult(ItemID.IceSkates, 1);
            recipe5.anyIronBar = true;
            recipe5.AddRecipe();
            ModRecipe recipe6 = new ModRecipe(this);
            recipe6.AddIngredient(ItemID.TungstenBar, 10);
            recipe6.AddIngredient(ItemID.IronBar, 2);
            recipe6.AddIngredient(ItemID.SnowBlock, 30);
            recipe6.AddTile(TileID.HeavyWorkBench);
            recipe6.SetResult(ItemID.IceSkates, 1);
            recipe6.anyIronBar = true;
            recipe6.AddRecipe();

            ModRecipe recipe7 = new ModRecipe(this);
            recipe7.AddIngredient(ItemID.Silk, 10);
            recipe7.AddIngredient(ItemID.SwiftnessPotion, 5);
            recipe7.AddTile(TileID.HeavyWorkBench);
            recipe7.SetResult(ItemID.HermesBoots, 1);
            recipe7.AddRecipe();
            ModRecipe recipe8 = new ModRecipe(this);
            recipe8.AddIngredient(ItemID.Silk, 10);
            recipe8.AddIngredient(ItemID.WaterWalkingPotion, 5);
            recipe8.AddTile(TileID.HeavyWorkBench);
            recipe8.SetResult(ItemID.WaterWalkingBoots, 1);
            recipe8.AddRecipe();
            ModRecipe recipe9 = new ModRecipe(this);
            recipe9.AddIngredient(ItemID.Vine, 2);
            recipe9.AddIngredient(ItemID.JungleSpores, 7);
            recipe9.AddIngredient(ItemID.PinkGel, 5);
            recipe9.AddTile(TileID.HeavyWorkBench);
            recipe9.SetResult(ItemID.AnkletoftheWind, 1);
            recipe9.AddRecipe();
            ModRecipe recipe10 = new ModRecipe(this);
            recipe10.AddIngredient(ItemID.IronBar, 2);
            recipe10.AddIngredient(ItemID.Silk, 1);
            recipe10.AddTile(TileID.HeavyWorkBench);
            recipe10.SetResult(ItemID.Aglet, 1);
            recipe10.anyIronBar = true;
            recipe10.AddRecipe();

            ModRecipe recipe11 = new ModRecipe(this);
            recipe11.AddIngredient(ItemID.IronBar, 5);
            recipe11.AddIngredient(ItemID.Chain, 1);
            recipe11.AddTile(TileID.HeavyWorkBench);
            recipe11.SetResult(ItemID.Radar, 1);
            recipe11.anyIronBar = true;
            recipe11.AddRecipe();
            ModRecipe recipe12 = new ModRecipe(this);
            recipe12.AddIngredient(ItemID.BlackLens, 1);
            recipe12.AddIngredient(ItemID.PinkGel, 5);
            recipe12.AddIngredient(ItemID.IronBar, 5);
            recipe12.AddTile(TileID.HeavyWorkBench);
            recipe12.SetResult(ItemID.LifeformAnalyzer, 1);
            recipe12.anyIronBar = true;
            recipe12.AddRecipe();
            ModRecipe recipe13 = new ModRecipe(this);
            recipe13.AddIngredient(ItemID.IronBar, 10);
            recipe13.AddIngredient(ItemID.Bone, 15);
            recipe13.AddTile(TileID.HeavyWorkBench);
            recipe13.SetResult(ItemID.TallyCounter, 1);
            recipe13.anyIronBar = true;
            recipe13.AddRecipe();
            ModRecipe recipe14 = new ModRecipe(this);
            recipe14.AddIngredient(ItemID.IronBar, 10);
            recipe14.AddIngredient(ItemID.Wire, 15);
            recipe14.AddTile(TileID.HeavyWorkBench);
            recipe14.SetResult(ItemID.MetalDetector, 1);
            recipe14.anyIronBar = true;
            recipe14.AddRecipe();
            ModRecipe recipe15 = new ModRecipe(this);
            recipe15.AddIngredient(ItemID.IronBar, 10);
            recipe15.AddIngredient(ItemID.Glass, 15);
            recipe15.AddIngredient(ItemID.FallenStar, 3);
            recipe15.AddTile(TileID.HeavyWorkBench);
            recipe15.SetResult(ItemID.MagicMirror, 1);
            recipe15.anyIronBar = true;
            recipe15.AddRecipe();

            ModRecipe recipe16 = new ModRecipe(this);
            recipe16.AddIngredient(ItemID.IronBar, 10);
            recipe16.AddIngredient(ItemID.Obsidian, 15);
            recipe16.AddIngredient(ItemID.Fireblossom, 3);
            recipe16.AddTile(TileID.HeavyWorkBench);
            recipe16.SetResult(ItemID.LavaCharm, 1);
            recipe16.anyIronBar = true;
            recipe16.AddRecipe();

            ModRecipe recipe17 = new ModRecipe(this);
            recipe17.AddIngredient(ItemID.Bottle, 1);
            recipe17.AddIngredient(ItemID.Cloud, 10);
            recipe17.AddIngredient(ItemID.Feather, 5);
            recipe17.AddTile(TileID.HeavyWorkBench);
            recipe17.SetResult(ItemID.CloudinaBottle, 1);
            recipe17.AddRecipe();
            ModRecipe recipe18 = new ModRecipe(this);
            recipe18.AddIngredient(ItemID.Bottle, 1);
            recipe18.AddIngredient(ItemID.SnowBlock, 50);
            recipe18.AddIngredient(ItemID.Shiverthorn, 5);
            recipe18.AddIngredient(ItemID.Feather, 5);
            recipe18.AddTile(TileID.HeavyWorkBench);
            recipe18.SetResult(ItemID.BlizzardinaBottle, 1);
            recipe18.AddRecipe();
            ModRecipe recipe19 = new ModRecipe(this);
            recipe19.AddIngredient(ItemID.Bottle, 1);
            recipe19.AddIngredient(ItemID.SandBlock, 100);
            recipe19.AddIngredient(ItemID.AntlionMandible, 5);
            recipe19.AddIngredient(ItemID.Feather, 5);
            recipe19.AddTile(TileID.HeavyWorkBench);
            recipe19.SetResult(ItemID.SandstorminaBottle, 1);
            recipe19.anyIronBar = true;
            recipe19.AddRecipe();

            ModRecipe recipe20 = new ModRecipe(this);
            recipe20.AddIngredient(ItemID.GoldBar, 10);
            recipe20.AddIngredient(ItemID.Cloud, 10);
            recipe20.AddIngredient(ItemID.Feather, 5);
            recipe20.AddTile(TileID.HeavyWorkBench);
            recipe20.SetResult(ItemID.LuckyHorseshoe, 1);
            recipe20.AddRecipe();
            ModRecipe recipe21 = new ModRecipe(this);
            recipe21.AddIngredient(ItemID.PlatinumBar, 10);
            recipe21.AddIngredient(ItemID.Cloud, 10);
            recipe21.AddIngredient(ItemID.Feather, 5);
            recipe21.AddTile(TileID.HeavyWorkBench);
            recipe21.SetResult(ItemID.LuckyHorseshoe, 1);
            recipe21.AddRecipe();
            ModRecipe recipe22 = new ModRecipe(this);
            recipe22.AddIngredient(ItemID.Gel, 10);
            recipe22.AddIngredient(ItemID.Cloud, 10);
            recipe22.AddIngredient(ItemID.Feather, 5);
            recipe22.AddIngredient(ItemID.WhiteString, 1);
            recipe22.AddTile(TileID.HeavyWorkBench);
            recipe22.SetResult(ItemID.ShinyRedBalloon, 1);
            recipe22.AddRecipe();

            ModRecipe recipe23 = new ModRecipe(this);
            recipe23.AddIngredient(ItemID.LifeCrystal, 1);
            recipe23.AddIngredient(ItemID.IronBar, 10);
            recipe23.AddIngredient(ItemID.Silk, 10);
            recipe23.anyIronBar = true;
            recipe23.AddTile(TileID.HeavyWorkBench);
            recipe23.SetResult(ItemID.BandofRegeneration, 1);
            recipe23.AddRecipe();
            ModRecipe recipe24 = new ModRecipe(this);
            recipe24.AddIngredient(ItemID.ManaCrystal, 1);
            recipe24.AddIngredient(ItemID.IronBar, 10);
            recipe24.AddIngredient(ItemID.Silk, 10);
            recipe24.anyIronBar = true;
            recipe24.AddTile(TileID.HeavyWorkBench);
            recipe24.SetResult(ItemID.BandofStarpower, 1);
            recipe24.AddRecipe();

            ModRecipe recipe25 = new ModRecipe(this);
            recipe25.AddIngredient(ItemID.Lens, 10);
            recipe25.AddIngredient(ItemID.DemoniteBar, 10);
            recipe25.AddIngredient(ItemID.Silk, 10);
            recipe25.anyIronBar = true;
            recipe25.AddTile(TileID.HeavyWorkBench);
            recipe25.SetResult(ItemID.Binoculars, 1);
            recipe25.AddRecipe();
            ModRecipe recipe26 = new ModRecipe(this);
            recipe26.AddIngredient(ItemID.Lens, 10);
            recipe26.AddIngredient(ItemID.CrimtaneBar, 10);
            recipe26.AddIngredient(ItemID.Silk, 10);
            recipe26.anyIronBar = true;
            recipe26.AddTile(TileID.HeavyWorkBench);
            recipe26.SetResult(ItemID.Binoculars, 1);
            recipe26.AddRecipe();

            ModRecipe recipe27 = new ModRecipe(this);
            recipe27.AddIngredient(ItemID.IronBar, 5);
            recipe27.AddIngredient(ItemID.GoldWatch, 1);
            recipe27.AddIngredient(ItemID.Silk, 3);
            recipe27.anyIronBar = true;
            recipe27.AddTile(TileID.HeavyWorkBench);
            recipe27.SetResult(ItemID.Stopwatch, 1);
            recipe27.AddRecipe();
            ModRecipe recipe28 = new ModRecipe(this);
            recipe28.AddIngredient(ItemID.IronBar, 5);
            recipe28.AddIngredient(ItemID.PlatinumWatch, 1);
            recipe28.AddIngredient(ItemID.Silk, 3);
            recipe28.anyIronBar = true;
            recipe28.AddTile(TileID.HeavyWorkBench);
            recipe28.SetResult(ItemID.Stopwatch, 1);
            recipe28.AddRecipe();

            ModRecipe recipe29 = new ModRecipe(this);
            recipe29.AddIngredient(ItemID.TatteredCloth, 3);
            recipe29.AddIngredient(ItemID.IronBar, 10);
            recipe29.AddIngredient(ItemID.Silk, 10);
            recipe29.anyIronBar = true;
            recipe29.AddTile(TileID.HeavyWorkBench);
            recipe29.SetResult(ItemID.DPSMeter, 1);
            recipe29.AddRecipe();

            ModRecipe recipe30 = new ModRecipe(this);
            recipe30.AddIngredient(ItemID.Sunflower, 1);
            recipe30.AddIngredient(ItemID.RainCloud, 1);
            recipe30.AddIngredient(ItemID.Feather, 5);
            recipe30.AddIngredient(ItemID.IronBar, 10);
            recipe30.anyIronBar = true;
            recipe30.AddTile(TileID.HeavyWorkBench);
            recipe30.SetResult(ItemID.WeatherRadio, 1);
            recipe30.AddRecipe();
            ModRecipe recipe31 = new ModRecipe(this);
            recipe31.AddIngredient(ItemID.CopperBar, 5);
            recipe31.AddIngredient(ItemID.FallenStar, 1);
            recipe31.AddIngredient(ItemID.Lens, 5);
            recipe31.AddIngredient(ItemID.IronBar, 10);
            recipe31.anyIronBar = true;
            recipe31.AddTile(TileID.HeavyWorkBench);
            recipe31.SetResult(ItemID.Sextant, 1);
            recipe31.AddRecipe();
            ModRecipe recipe32 = new ModRecipe(this);
            recipe32.AddIngredient(ItemID.TinBar, 5);
            recipe32.AddIngredient(ItemID.FallenStar, 1);
            recipe32.AddIngredient(ItemID.Lens, 5);
            recipe32.AddIngredient(ItemID.IronBar, 10);
            recipe32.anyIronBar = true;
            recipe32.AddTile(TileID.HeavyWorkBench);
            recipe32.SetResult(ItemID.Sextant, 1);
            recipe32.AddRecipe();
            ModRecipe recipe33 = new ModRecipe(this);
            recipe33.AddIngredient(ItemID.Bass, 1);
            recipe33.AddIngredient(ItemID.Book, 4);
            recipe33.anyIronBar = true;
            recipe33.AddTile(TileID.HeavyWorkBench);
            recipe33.SetResult(ItemID.FishermansGuide, 1);
            recipe33.AddRecipe();

            ModRecipe recipe34 = new ModRecipe(this);
            recipe34.AddIngredient(ItemID.Wood, 20);
            recipe34.AddIngredient(ItemID.Silk, 5);
            recipe34.AddTile(TileID.Sawmill);
            recipe34.SetResult(ItemID.LivingLoom, 1);
            recipe34.AddRecipe();
            ModRecipe recipe35 = new ModRecipe(this);
            recipe35.AddIngredient(ItemID.IronBar, 10);
            recipe35.AddIngredient(ItemID.StoneBlock, 20);
            recipe35.AddIngredient(ItemID.FallenStar, 5);
            recipe35.AddIngredient(ItemID.Silk, 5);
            recipe35.AddIngredient(ItemID.Feather, 5);
            recipe35.anyIronBar = true;
            recipe35.AddTile(TileID.HeavyWorkBench);
            recipe35.SetResult(ItemID.SkyMill, 1);
            recipe35.AddRecipe();
            ModRecipe recipe36 = new ModRecipe(this);
            recipe36.AddIngredient(ItemID.Wood, 10);
            recipe36.AddIngredient(ItemID.BeeWax, 5);
            recipe36.AddIngredient(ItemID.Silk, 5);
            recipe36.AddTile(TileID.LivingLoom);
            recipe36.SetResult(ItemID.HoneyDispenser, 1);
            recipe36.AddRecipe();
            ModRecipe recipe37 = new ModRecipe(this);
            recipe37.AddIngredient(ItemID.StoneBlock, 10);
            recipe37.AddIngredient(ItemID.Bone, 15);
            recipe37.AddIngredient(ItemID.IronBar, 5);
            recipe37.anyIronBar = true;
            recipe37.AddTile(TileID.HeavyWorkBench);
            recipe37.SetResult(ItemID.BoneWelder, 1);
            recipe37.AddRecipe();
            ModRecipe recipe38 = new ModRecipe(this);
            recipe38.AddIngredient(ItemID.StoneBlock, 10);
            recipe38.AddIngredient(ItemID.IceBlock, 25);
            recipe38.AddIngredient(ItemID.IronBar, 5);
            recipe38.anyIronBar = true;
            recipe38.AddTile(TileID.HeavyWorkBench);
            recipe38.SetResult(ItemID.IceMachine, 1);
            recipe38.AddRecipe();
            ModRecipe recipe39 = new ModRecipe(this);
            recipe39.AddIngredient(ItemID.Furnace, 1);
            recipe39.AddIngredient(ItemID.Obsidian, 15);
            recipe39.AddIngredient(ItemID.LavaBucket, 1);
            recipe39.AddTile(TileID.WorkBenches);
            recipe39.SetResult(ItemID.Hellforge, 1);
            recipe39.AddRecipe();
            ModRecipe recipe40 = new ModRecipe(this);
            recipe40.AddIngredient(ItemID.Wood, 20);
            recipe40.AddIngredient(ItemID.Bone, 15);
            recipe40.AddIngredient(ItemID.IronBar, 5);
            recipe40.AddIngredient(ItemID.Bottle, 5);
            recipe40.anyIronBar = true;
            recipe40.AddTile(TileID.LivingLoom);
            recipe40.SetResult(ItemID.AlchemyTable, 1);
            recipe40.AddRecipe();

            ModRecipe recipe41 = new ModRecipe(this);
            recipe41.AddIngredient(ItemID.Vine, 1);
            recipe41.AddIngredient(ItemID.JungleSpores, 1);
            recipe41.AddIngredient(ItemID.Fireblossom, 1);
            recipe41.AddTile(TileID.LivingLoom);
            recipe41.SetResult(ItemID.JungleRose, 1);
            recipe41.AddRecipe();
            ModRecipe recipe42 = new ModRecipe(this);
            recipe42.AddIngredient(ItemID.Vine, 1);
            recipe42.AddIngredient(ItemID.JungleSpores, 1);
            recipe42.AddIngredient(ItemID.ManaCrystal, 1);
            recipe42.AddTile(TileID.LivingLoom);
            recipe42.SetResult(ItemID.NaturesGift, 1);
            recipe42.AddRecipe();
            ModRecipe recipe43 = new ModRecipe(this);
            recipe43.AddIngredient(ItemID.Obsidian, 15);
            recipe43.AddIngredient(ItemID.JungleRose, 1);
            recipe43.AddTile(TileID.Hellforge);
            recipe43.SetResult(ItemID.ObsidianRose, 1);
            recipe43.AddRecipe();

            ModRecipe recipe44 = new ModRecipe(this);
            recipe44.AddIngredient(ItemID.Vine, 3);
            recipe44.AddIngredient(ItemID.JungleSpores, 10);
            recipe44.AddIngredient(ItemID.Silk, 6);
            recipe44.AddTile(TileID.LivingLoom);
            recipe44.SetResult(ItemID.FeralClaws, 1);
            recipe44.AddRecipe();
            ModRecipe recipe45 = new ModRecipe(this);
            recipe45.AddIngredient(ItemID.Vine, 3);
            recipe45.AddIngredient(ItemID.Book, 4);
            recipe45.AddTile(TileID.LivingLoom);
            recipe45.SetResult(ItemID.CordageGuide, 1);
            recipe45.AddRecipe();
            ModRecipe recipe46 = new ModRecipe(this);
            recipe46.AddIngredient(ItemID.Vine, 3);
            recipe46.AddIngredient(ItemID.JungleSpores, 10);
            recipe46.AddIngredient(ItemID.RichMahogany, 10);
            recipe46.AddIngredient(ItemID.JungleRose, 1);
            recipe46.AddTile(TileID.LivingLoom);
            recipe46.SetResult(ItemID.StaffofRegrowth, 1);
            recipe46.AddRecipe();
            ModRecipe recipe47 = new ModRecipe(this);
            recipe47.AddIngredient(ItemID.Vine, 3);
            recipe47.AddIngredient(ItemID.JungleSpores, 3);
            recipe47.AddIngredient(ItemID.Silk, 10);
            recipe47.AddIngredient(ItemID.JungleRose, 1);
            recipe47.AddTile(TileID.LivingLoom);
            recipe47.SetResult(ItemID.FlowerBoots, 1);
            recipe47.AddRecipe();

            ModRecipe recipe48 = new ModRecipe(this);
            recipe48.AddIngredient(ItemID.Chain, 3);
            recipe48.AddIngredient(ItemID.IronBar, 3);
            recipe48.anyIronBar = true;
            recipe48.AddTile(TileID.HeavyWorkBench);
            recipe48.SetResult(ItemID.ClimbingClaws, 1);
            recipe48.AddRecipe();
            ModRecipe recipe49 = new ModRecipe(this);
            recipe49.AddIngredient(ItemID.Chain, 3);
            recipe49.AddIngredient(ItemID.IronBar, 3);
            recipe49.anyIronBar = true;
            recipe49.AddTile(TileID.HeavyWorkBench);
            recipe49.SetResult(ItemID.ShoeSpikes, 1);
            recipe49.AddRecipe();

            ModRecipe recipe50 = new ModRecipe(this);
            recipe50.AddIngredient(ItemID.TeleportationPotion, 3);
            recipe50.AddIngredient(ItemID.CrystalShard, 12);
            recipe50.AddIngredient(ItemID.UnicornHorn, 1);
            recipe50.AddTile(TileID.CrystalBall);
            recipe50.SetResult(ItemID.RodofDiscord, 1);
            recipe50.AddRecipe();

            ModRecipe recipe51 = new ModRecipe(this);
            recipe51.AddIngredient(ItemID.CobaltBar, 12);
            recipe51.AddTile(TileID.Anvils);
            recipe51.SetResult(ItemID.CobaltShield, 1);
            recipe51.AddRecipe();
            ModRecipe recipe52 = new ModRecipe(this);
            recipe52.AddIngredient(ItemID.PalladiumBar, 12);
            recipe52.AddTile(TileID.Anvils);
            recipe52.SetResult(ItemID.CobaltShield, 1);
            recipe52.AddRecipe();
            ModRecipe recipe53 = new ModRecipe(this);
            recipe53.AddIngredient(ItemID.CobaltBar, 12);
            recipe53.AddTile(TileID.Anvils);
            recipe53.SetResult(ItemID.Muramasa, 1);
            recipe53.AddRecipe();
            ModRecipe recipe54 = new ModRecipe(this);
            recipe54.AddIngredient(ItemID.PalladiumBar, 12);
            recipe54.AddTile(TileID.Anvils);
            recipe54.SetResult(ItemID.Muramasa, 1);
            recipe54.AddRecipe();
            ModRecipe recipe55 = new ModRecipe(this);
            recipe55.AddIngredient(ItemID.GoldenKey, 3);
            recipe55.AddIngredient(ItemID.Obsidian, 15);
            recipe55.AddTile(TileID.HeavyWorkBench);
            recipe55.SetResult(ItemID.ShadowKey, 1);
            recipe55.AddRecipe();

            ModRecipe recipe56 = new ModRecipe(this);
            recipe56.AddIngredient(ItemID.Gel, 25);
            recipe56.AddIngredient(ItemID.Glowstick, 25);
            recipe56.AddIngredient(ItemID.Leather, 3);
            recipe56.AddTile(TileID.HeavyWorkBench);
            recipe56.SetResult(ItemID.FrogLeg, 1);
            recipe56.AddRecipe();
            ModRecipe recipe57 = new ModRecipe(this);
            recipe57.AddIngredient(ItemID.Gel, 25);
            recipe57.AddIngredient(ItemID.Glowstick, 25);
            recipe57.AddIngredient(ItemID.Silk, 3);
            recipe57.AddTile(TileID.HeavyWorkBench);
            recipe57.SetResult(ItemID.JellyfishNecklace, 1);
            recipe57.AddRecipe();
            ModRecipe recipe58 = new ModRecipe(this);
            recipe58.AddIngredient(ItemID.Gel, 25);
            recipe58.AddIngredient(ItemID.Leather, 3);
            recipe58.AddIngredient(ItemID.SharkFin, 1);
            recipe58.AddTile(TileID.HeavyWorkBench);
            recipe58.SetResult(ItemID.Flipper, 1);
            recipe58.AddRecipe();
            ModRecipe recipe59 = new ModRecipe(this);
            recipe59.AddIngredient(ItemID.IronBar, 15);
            recipe59.AddIngredient(ItemID.Cloud, 5);
            recipe59.AddIngredient(ItemID.SharkFin, 5);
            recipe59.anyIronBar = true;
            recipe59.AddTile(TileID.HeavyWorkBench);
            recipe59.SetResult(ItemID.DivingHelmet, 1);
            recipe59.AddRecipe();
            ModRecipe recipe60 = new ModRecipe(this);
            recipe60.AddIngredient(ItemID.IronBar, 15);
            recipe60.AddIngredient(ItemID.Chain, 5);
            recipe60.AddIngredient(ItemID.SharkFin, 1);
            recipe60.anyIronBar = true;
            recipe60.AddTile(TileID.HeavyWorkBench);
            recipe60.SetResult(ItemID.SharkToothNecklace, 1);
            recipe60.AddRecipe();

            ModRecipe recipe61 = new ModRecipe(this);
            recipe61.AddIngredient(ItemID.IronBar, 15);
            recipe61.AddIngredient(ItemID.ManaCrystal, 1);
            recipe61.AddIngredient(ItemID.HeartreachPotion, 3);
            recipe61.anyIronBar = true;
            recipe61.AddTile(TileID.HeavyWorkBench);
            recipe61.SetResult(ItemID.CelestialMagnet, 1);
            recipe61.AddRecipe();
            ModRecipe recipe62 = new ModRecipe(this);
            recipe62.AddIngredient(ItemID.IceBlock, 50);
            recipe62.AddIngredient(ItemID.TurtleShell, 1);
            recipe62.AddTile(TileID.HeavyWorkBench);
            recipe62.SetResult(ItemID.FrozenTurtleShell, 1);
            recipe62.AddRecipe();
            ModRecipe recipe63 = new ModRecipe(this);
            recipe63.AddIngredient(ItemID.FallenStar, 5);
            recipe63.AddIngredient(ItemID.EndlessQuiver, 1);
            recipe63.AddTile(TileID.HeavyWorkBench);
            recipe63.SetResult(ItemID.MagicQuiver, 1);
            recipe63.AddRecipe();
            ModRecipe recipe64 = new ModRecipe(this);
            recipe64.AddIngredient(ItemID.HallowedBar, 15);
            recipe64.AddIngredient(ItemID.Ectoplasm, 15);
            recipe64.AddTile(TileID.HeavyWorkBench);
            recipe64.SetResult(ItemID.PaladinsShield, 1);
            recipe64.AddRecipe();
            ModRecipe recipe65 = new ModRecipe(this);
            recipe65.AddIngredient(ItemID.HellstoneBar, 5);
            recipe65.AddIngredient(ItemID.Fireblossom, 5);
            recipe65.AddTile(TileID.HeavyWorkBench);
            recipe65.SetResult(ItemID.MagmaStone, 1);
            recipe65.AddRecipe();

            ModRecipe recipe66 = new ModRecipe(this);
            recipe66.AddIngredient(ItemID.IronBar, 15);
            recipe66.AddIngredient(ItemID.Lens, 5);
            recipe66.AddIngredient(ItemID.Ectoplasm, 15);
            recipe66.AddTile(TileID.HeavyWorkBench);
            recipe66.SetResult(ItemID.RifleScope, 1);
            recipe66.AddRecipe();
            ModRecipe recipe67 = new ModRecipe(this);
            recipe67.AddIngredient(ItemID.Silk, 15);
            recipe67.AddIngredient(ItemID.BlackInk, 1);
            recipe67.AddIngredient(ItemID.Ectoplasm, 5);
            recipe67.AddTile(TileID.HeavyWorkBench);
            recipe67.SetResult(ItemID.Tabi, 1);
            recipe67.AddRecipe();
            ModRecipe recipe68 = new ModRecipe(this);
            recipe68.AddIngredient(ItemID.Silk, 15);
            recipe68.AddIngredient(ItemID.BlackInk, 1);
            recipe68.AddIngredient(ItemID.Ectoplasm, 10);
            recipe68.AddTile(TileID.HeavyWorkBench);
            recipe68.SetResult(ItemID.BlackBelt, 1);
            recipe68.AddRecipe();

            ModRecipe ankh1 = new ModRecipe(this);
            ankh1.AddIngredient(ItemID.Leather, 6);
            ankh1.AddIngredient(ItemID.Silk, 6);
            ankh1.AddIngredient(ItemID.SoulofNight, 5);
            ankh1.AddTile(TileID.HeavyWorkBench);
            ankh1.SetResult(ItemID.AdhesiveBandage, 1);
            ankh1.AddRecipe();
            ModRecipe ankh2 = new ModRecipe(this);
            ankh2.AddIngredient(ItemID.Bone, 30);
            ankh2.AddIngredient(ItemID.IronBar, 6);
            ankh2.AddIngredient(ItemID.SoulofNight, 5);
            ankh2.anyIronBar = true;
            ankh2.AddTile(TileID.HeavyWorkBench);
            ankh2.SetResult(ItemID.ArmorPolish, 1);
            ankh2.AddRecipe();
            ModRecipe ankh3 = new ModRecipe(this);
            ankh3.AddIngredient(ItemID.JungleSpores, 15);
            ankh3.AddIngredient(ItemID.Stinger, 15);
            ankh3.AddIngredient(ItemID.Gel, 15);
            ankh3.AddTile(TileID.HeavyWorkBench);
            ankh3.SetResult(ItemID.Bezoar, 1);
            ankh3.AddRecipe();
            ModRecipe ankh4 = new ModRecipe(this);
            ankh4.AddIngredient(ItemID.Silk, 16);
            ankh4.AddIngredient(ItemID.SoulofNight, 15);
            ankh4.AddTile(TileID.HeavyWorkBench);
            ankh4.SetResult(ItemID.Blindfold, 1);
            ankh4.AddRecipe();
            ModRecipe ankh5 = new ModRecipe(this);
            ankh5.AddIngredient(ItemID.Wire, 30);
            ankh5.AddIngredient(ItemID.IronBar, 15);
            ankh5.AddIngredient(ItemID.SoulofLight, 15);
            ankh5.anyIronBar = true;
            ankh5.AddTile(TileID.HeavyWorkBench);
            ankh5.SetResult(ItemID.FastClock, 1);
            ankh5.AddRecipe();
            ModRecipe ankh6 = new ModRecipe(this);
            ankh6.AddIngredient(ItemID.Wire, 30);
            ankh6.AddIngredient(ItemID.IronBar, 15);
            ankh6.AddIngredient(ItemID.SoulofFlight, 15);
            ankh6.anyIronBar = true;
            ankh6.AddTile(TileID.HeavyWorkBench);
            ankh6.SetResult(ItemID.Megaphone, 1);
            ankh6.AddRecipe();
            ModRecipe ankh7 = new ModRecipe(this);
            ankh7.AddIngredient(ItemID.Lens, 30);
            ankh7.AddIngredient(ItemID.IronBar, 15);
            ankh7.AddIngredient(ItemID.SoulofNight, 15);
            ankh7.anyIronBar = true;
            ankh7.AddTile(TileID.HeavyWorkBench);
            ankh7.SetResult(ItemID.Nazar, 1);
            ankh7.AddRecipe();
            ModRecipe ankh8 = new ModRecipe(this);
            ankh8.AddIngredient(ItemID.Book, 6);
            ankh8.AddIngredient(ItemID.SoulofFlight, 15);
            ankh8.AddTile(TileID.HeavyWorkBench);
            ankh8.SetResult(ItemID.TrifoldMap, 1);
            ankh8.AddRecipe();
            ModRecipe ankh9 = new ModRecipe(this);
            ankh9.AddIngredient(ItemID.Waterleaf, 2);
            ankh9.AddIngredient(ItemID.Fireblossom, 2);
            ankh9.AddIngredient(ItemID.Blinkroot, 3);
            ankh9.AddIngredient(ItemID.SoulofFlight, 5);
            ankh9.AddIngredient(ItemID.BottledWater, 1);
            ankh9.alchemy = true;
            ankh9.AddTile(TileID.AlchemyTable);
            ankh9.SetResult(ItemID.Vitamins, 1);
            ankh9.AddRecipe();

            ModRecipe leather1 = new ModRecipe(this);
            leather1.AddIngredient(ItemID.Gel, 10);
            leather1.AddIngredient(ItemID.Silk, 10);
            leather1.AddTile(TileID.DemonAltar);
            leather1.SetResult(ItemID.Leather, 2);
			leather1.AddRecipe();
            ModRecipe leather2 = new ModRecipe(this);
            leather2.AddIngredient(ItemID.Leather, 2);
            leather2.AddIngredient(ItemID.Silk, 6);
            leather2.AddTile(TileID.DemonAltar);
            leather2.SetResult(ItemID.Book, 2);
			leather2.AddRecipe();
            ModRecipe leather3 = new ModRecipe(this);
            leather3.AddIngredient(ItemID.Leather, 2);
            leather3.AddIngredient(ItemID.Silk, 8);
            leather3.AddTile(TileID.DemonAltar);
            leather3.SetResult(ItemID.TatteredCloth, 2);
			leather3.AddRecipe();

            ModRecipe recipe69 = new ModRecipe(this);
            recipe69.AddIngredient(ItemID.Wood, 25);
            recipe69.AddIngredient(ItemID.FallenStar, 5);
            recipe69.AddIngredient(ItemID.Gel, 50);
            recipe69.AddTile(TileID.LivingLoom);
            recipe69.SetResult(ItemID.SlimeStaff, 1);
            recipe69.AddRecipe();
            ModRecipe recipe70 = new ModRecipe(this);
            recipe70.AddIngredient(ItemID.IronBar, 25);
            recipe70.AddIngredient(ItemID.FallenStar, 5);
            recipe70.AddIngredient(ItemID.MiningHelmet, 1);
            recipe70.anyIronBar = true;
            recipe70.AddTile(TileID.HeavyWorkBench);
            recipe70.SetResult(ItemID.EnchantedSword, 1);
            recipe70.AddRecipe();
            ModRecipe recipe71 = new ModRecipe(this);
            recipe71.AddIngredient(ItemID.IronBar, 25);
            recipe71.AddIngredient(ItemID.Vine, 5);
            recipe71.AddIngredient(ItemID.JungleSpores, 15);
            recipe71.AddIngredient(ItemID.Stinger, 15);
            recipe71.AddIngredient(ItemID.RichMahogany, 50);
            recipe71.anyIronBar = true;
            recipe71.AddTile(TileID.HeavyWorkBench);
            recipe71.SetResult(ItemID.Boomstick, 1);
            recipe71.AddRecipe();
            ModRecipe recipe72 = new ModRecipe(this);
            recipe72.AddIngredient(ItemID.Book, 1);
            recipe72.AddIngredient(ItemID.WaterBucket, 1);
            recipe72.AddIngredient(ItemID.DemoniteBar, 15);
            recipe72.AddTile(TileID.Bookcases);
            recipe72.SetResult(ItemID.WaterBolt, 1);
            recipe72.AddRecipe();
            ModRecipe recipe73 = new ModRecipe(this);
            recipe73.AddIngredient(ItemID.Book, 1);
            recipe73.AddIngredient(ItemID.WaterBucket, 1);
            recipe73.AddIngredient(ItemID.CrimtaneBar, 15);
            recipe73.AddTile(TileID.Bookcases);
            recipe73.SetResult(ItemID.WaterBolt, 1);
            recipe73.AddRecipe();

            base.AddRecipes();
        }
        public override void Unload()
        {
            Instance = null;
        }
    }
}